package com.example.helloworld;

import static com.codename1.ui.CN.*;
import com.codename1.system.Lifecycle;
import com.codename1.ui.*;
import com.codename1.ui.layouts.*;
import com.codename1.io.*;
import com.codename1.ui.plaf.*;
import com.codename1.ui.util.Resources;

/**
 * This file was generated by <a href="https://www.codenameone.com/">Codename One</a> for the purpose
 * of building native mobile applications using Java.
 */
public class HelloWorldHexJavaCodenameOne extends Lifecycle {
    @Override
    public void runApp() {
        Form greeting = new Form("Hello World", BoxLayout.y());
        greeting.show();
    }
}
