package com.example.helloworld;

import com.codename1.system.Lifecycle;
import com.codename1.ui.*;
import com.codename1.ui.layouts.*;
import com.example.adaptors.output.InMemoryGreetingRepository;
import com.example.core.GreetingService;
import com.example.core.ports.input.GreetingUseCase;
import com.example.core.ports.output.GreetingRepository;

/**
 * This file was generated by <a href="https://www.codenameone.com/">Codename One</a> for the purpose
 * of building native mobile applications using Java.
 */
public class HelloWorldHexJavaCodenameOne extends Lifecycle {
    @Override
    public void runApp() {
        GreetingRepository greetingRepository = new InMemoryGreetingRepository();
        GreetingUseCase greetingService = new GreetingService(greetingRepository);
        Form greeting = new Form(greetingService.greet("Makeda").getMessage(), BoxLayout.y());
        greeting.show();
    }
}
